RTGetOptPrintError: Don't crash on VERR_GETOP_TINVALID_ARGUMENT_FORMAT if pDef is NULL.
git-svn-id: https://www.virtualbox.org/svn/vbox/trunk@56700 cfe28804-0f27-0410-a406-dd0f0b0b656f